grails-app/controllers/inventorysystem/CalendarController.groovy
package inventorysystem

import inventorysystem.utils.EventJSONTemplate
import inventorysystem.enums.Repeat

import grails.converters.JSON

class CalendarController {
    EventService eventService

    def index() {
        int currentYear = new Date().year + 1900;
        return [year: currentYear, outletList: Outlet.list(), merchTypeList: MerchType.list()]
    }

    def events() {

        List<EventJSONTemplate> result = new ArrayList<>()

        List<Long> outletIdList = params.list("outlet[]").collect {it.toLong()}
        Outlet.findAllByIdInList(outletIdList).each {
            String description = it.address

            List<Long> merchTypeIdList = params.list("merchType[]").collect {it.toLong()}
            it.merchTypes.findAll { merchTypeIdList.contains(it.id) }.each {
                result.addAll(eventService.getEventsForYear(it, description))
            }
        }
        render(result as JSON)
    }
}

grails-app/controllers/inventorysystem/OutletController.groovy
package inventorysystem



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class OutletController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Outlet.list(params), model: [outletInstanceCount: Outlet.count()]
    }

    def show(Outlet outletInstance) {
        respond outletInstance
    }

    def create() {
        respond new Outlet(params), model: [merchTypeList: MerchType.findAll()]
    }

    @Transactional
    def save(Outlet outletInstance) {
        params.list("merchType")?.each {outletInstance.addToMerchTypes(MerchType.get(it.toLong()))}
        if (outletInstance == null) {
            notFound()
            return
        }

        if (outletInstance.hasErrors()) {
            respond outletInstance.errors, view: 'create'
            return
        }

        outletInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'outletInstance.label', default: 'Outlet'), outletInstance.id])
                redirect outletInstance
            }
            '*' { respond outletInstance, [status: CREATED] }
        }
    }

    def edit(Outlet outletInstance) {
        respond outletInstance, model: [merchTypeList: MerchType.findAll()]
    }

    @Transactional
    def update(Outlet outletInstance) {
        outletInstance?.merchTypes?.clear()
        params.list("merchType")?.each {outletInstance.addToMerchTypes(MerchType.get(it.toLong()))}
        if (outletInstance == null) {
            notFound()
            return
        }

        if (outletInstance.hasErrors()) {
            respond outletInstance.errors, view: 'edit'
            return
        }

        outletInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Outlet.label', default: 'Outlet'), outletInstance.id])
                redirect outletInstance
            }
            '*' { respond outletInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Outlet outletInstance) {

        if (outletInstance == null) {
            notFound()
            return
        }

        outletInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Outlet.label', default: 'Outlet'), outletInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'outletInstance.label', default: 'Outlet'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Inventory System"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap.min.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'datepicker3.css')}" type="text/css">
		<g:javascript src="jquery-1.11.1.min.js"/>
		<g:javascript src="bootstrap.min.js"/>
		<g:javascript src="bootstrap-datepicker.js"/>
		<g:javascript library="application"/>
        <g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
        <div class="navbar" style="padding-top: 2%; padding-left: 1%;">
            <g:link controller="calendar" action="index" class="btn btn-primary btn-large">Графік інвентарізації</g:link>
            <g:link controller="merchType" action="index" class="btn btn-primary btn-large">Типи товарів</g:link>
            <g:link controller="outlet" action="index" class="btn btn-primary btn-large">Торгові точки</g:link>
            <g:link controller="report" action="index" class="btn btn-primary btn-large">Звіти</g:link>
            <g:link controller="logout" action="index" class="btn btn-primary btn-large">Вийти</g:link>
        </div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<r:layoutResources />
	</body>
</html>