grails-app/domain/inventorysystem/MerchType.groovy
package inventorysystem

import inventorysystem.enums.Repeat

class MerchType {

    String name
    Repeat repeat
    Integer daysInterval
    static hasMany = [dates: Date]

    static constraints = {
        name (blank: false, unique: true)
        repeat (blank: false, enumType: 'ordinal')
        daysInterval nullable: true
        dates nullable: true
    }
}

grails-app/domain/inventorysystem/Outlet.groovy
package inventorysystem

class Outlet {

    String address
    String phoneNumber
    static hasMany = [merchTypes : MerchType]

    static constraints = {
        address (blank: false, unique: true)
        phoneNumber (nullable: true)
        merchTypes (nullable: true)
    }
}

grails-app/domain/inventorysystem/Report.groovy
package inventorysystem

class Report {

    String responsiblePerson
    Outlet outlet
    static hasMany = [supReports: SubReport]

    static constraints = {
        responsiblePerson blank: false
    }
}

grails-app/controllers/inventorysystem/ReportController.groovy
package inventorysystem

import grails.plugin.springsecurity.SpringSecurityService
import grails.transaction.Transactional
import inventorysystem.utils.EventJSONTemplate

import java.text.SimpleDateFormat

@Transactional(readOnly = true)
class ReportController {
    static allowedMethods = [save: "POST"]

    SpringSecurityService springSecurityService
    EventService eventService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Report.list(params), model:[ReportInstanceCount: Report.count()]
    }

    def choose() {
        return [outletList: Outlet.list(), merchTypeList: MerchType.list()]
    }

    def create() {
        User user = springSecurityService.currentUser.asType(User.class)
        Outlet outlet = Outlet.get(params.long("outlet"))
        Report report = new Report(
                outlet: outlet,
                responsiblePerson: user.firstName + " " + user.lastName
        )
        List<Long> merchTypeIdList = params.merchType.split(',').collect {it.toLong()}
        outlet.merchTypes.findAll {merchTypeIdList.contains(it.id)} .each {
            SubReport subReport = new SubReport();
            subReport.merchType = it;

            List<EventJSONTemplate> events = eventService.getEventsForYear(it, null).sort {it.date}
            events = events.reverse()

            Date now = new Date().clearTime()
            Date plannedDate
            if(!events.empty){
                plannedDate = new Date(events.find {it.date.toLong() <= now.time} ?.date?.toLong() ?: events.last()?.date?.toLong()) //TODO: split the line
            } else {
                plannedDate = new Date()
            }
            subReport.plannedDate = plannedDate
            subReport.realDate = now

            report.addToSupReports subReport
        }

        return [report: report]
    }

    def show(Report reportInstance) {
        respond reportInstance
    }

    @Transactional
    def save() {
        Report report = new Report(
                outlet: Outlet.findByAddress(params.address),
                responsiblePerson: params.responsiblePerson
        )
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd")
        List<Integer> supposedToBeList = params.list('supposedToBe')?.collect {it.toInteger()}
        List<Integer> factList = params.list('fact')?.collect {it.toInteger()}
        List<Date> plannedDateList = params.list('plannedDate')?.collect {format.parse(it)}
        List<Date> realDateList = params.list('realDate')?.collect {format.parse(it)}
        params.list('merchType').eachWithIndex {merchType, i ->
            SubReport subReport = new SubReport(
                    merchType: MerchType.get(merchType.toLong()),
                    supposedToBe: supposedToBeList.get(i),
                    fact: factList.get(i),
                    plannedDate: plannedDateList.get(i),
                    realDate: realDateList.get(i)
            )
            report.addToSupReports subReport
        }
        report.save(flush: true)
        redirect(action: "show", id: report.id)
    }
}

grails-app/views/report/choose.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
    <head>
        <meta name="layout" content="main">
        <title>Створити звіт</title>
        <script type="text/javascript">
            function changeSelection(checkboxClass, status){
                $(checkboxClass).each(function() {
                    this.checked = status;
                });
            }
            function createReport(link){
                 var outletValue = $('input[name=outlet]:checked').val();

                var merchTypeValues = $('input:checkbox:checked.merchType').map(function () {
                    return this.value;
                }).get();

                if(merchTypeValues == ''){
                    $("#emptyError").show("slow");
                    return;
                }

                window.location.href = (link + "?outlet=" + outletValue + "&merchType=" + merchTypeValues);
            }
        </script>
    </head>
    <body>
        <h3 align="center">Створення звіту по інвентарізації</h3>
        <div id="emptyError" class="alert alert-danger" hidden="true">
            Необхідно відмітити хоча б один тип товару!
        </div>
        <table class="table">
            <tr>
                <td width="50%">
                    <h4>Торгові точки:</h4>
                    <g:each in="${outletList}" var="outlet">
                        <div class="checkbox">
                            <label for="outlet">${outlet.address}</label>
                            <g:radio name="outlet" class="outlet" value="${outlet.id}" checked="true"/>
                        </div>
                    </g:each>
                </td>
                <td width="50%">
                    <h4>Типи товарів:</h4>
                    <g:each in="${merchTypeList}" var="merchType">
                        <div class="checkbox">
                            <label for="merchType">${merchType.name}</label>
                            <g:checkBox name="merchType" class="merchType" value="${merchType.id}" checked="true"/>
                        </div>
                    </g:each>
                    <button type="button" class="btn btn-success" onclick="changeSelection('.merchType', true)">Позначити</button>
                    <button type="button" class="btn btn-warning" onclick="changeSelection('.merchType', false)">Відмінити</button>
                </td>
            </tr>
        </table>
        <div align="center">
            <button type="button" class="btn btn-primary btn-lg" onclick="createReport('<g:createLink action="create" />')">
                Створити звіт
            </button>
        </div>
        <br>
    </body>
</html>

grails-app/views/report/create.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
      <meta name="layout" content="main">
      <title>Створити звіт</title>
</head>
<body>
<form action="<g:createLink action="save"/>" method="POST" role="form" style="padding-left: 5%; padding-right: 5%;">
    <div class="form-group">
        <label for="responsiblePerson">Відповідальна особа:</label>
        <input type="text" class="form-control" name="responsiblePerson" id="responsiblePerson" required
               value="${report.responsiblePerson}">
    </div>
    <div class="form-group">
        <label for="address">Адреса торгової точки:</label>
        <input type="text" class="form-control" name="address" id="address" required value="${report.outlet.address}">
    </div>
    <h3>Типи товарів:</h3>
    <table class="table table-bordered">
        <tr>
            <th>Товар
            <th>Повинно бути
            <th>Факт
            <th>Запланована дата
            <th>Фактична дата
        </tr>
        <g:each in="${report.supReports}" var="subReport">
            <tr>
                <td>
                    ${subReport.merchType.name}
                    <input type="hidden"" name="merchType" value="${subReport.merchType.id}" />
                </td>
                <td>
                    <input type="number" class="form-control" name="supposedToBe" required>
                </td>
                <td>
                    <input type="number" class="form-control" name="fact" required>
                </td>
                <td>
                    <input type="date" class="form-control" name="plannedDate" required
                           value="<g:formatDate format="yyyy-MM-dd" date="${subReport.plannedDate}"/>">
                </td>
                <td>
                    <input type="date" class="form-control" name="realDate" required
                           value="<g:formatDate format="yyyy-MM-dd" date="${subReport.realDate}"/>">
                </td>
            </tr>
        </g:each>
    </table>
    <br>
        <input class="btn btn-primary btn-lg" type="submit" value="Створити звіт">
    <br>
</form>
</body>
</html>

grails-app/views/report/index.gsp
<%@ page import="inventorysystem.Report" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <title>Звіти</title>
</head>
<body>
<a href="#list-report" class="skip" tabindex="-1">Перейти до вмісту&hellip;</a>
<div class="nav" role="navigation">
    <ul>
        <li><g:link class="btn btn-default" action="choose">Створити звіт</g:link></li>
    </ul>
</div>
<div id="list-report" class="content scaffold-list" role="main">
    <h1>Звіти:</h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="id" title="№" />

            <g:sortableColumn property="responsiblePerson" title="Відповідальна особа" />

            <g:sortableColumn property="outlet.address" title="Адресса торгової точки" />

        </tr>
        </thead>
        <tbody>
        <g:each in="${reportInstanceList}" status="i" var="reportInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show" id="${reportInstance.id}">${fieldValue(bean: reportInstance, field: "id")}</g:link></td>

                <td>${fieldValue(bean: reportInstance, field: "responsiblePerson")}</td>

                <td>${fieldValue(bean: reportInstance, field: "outlet.address")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>
    <div class="pagination">
        <g:paginate total="${reportInstanceCount ?: 0}" />
    </div>
</div>
</body>
</html>

grails-app/views/report/show.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main">
    <title>Звіт №${reportInstance.id}</title>
</head>
<body>
<div style="padding-left: 5%; padding-right: 5%;">
    <h2>Звіт №${reportInstance.id}</h2>
    <div class="form-group">
        <strong>Відповідальна особа:</strong> ${reportInstance.responsiblePerson}
    </div>
    <div class="form-group">
        <strong>Адреса торгової точки:</strong> ${reportInstance.outlet.address}
    </div>
    <h3>Типи товарів:</h3>
    <table class="table table-bordered">
        <tr>
            <th>Товар
            <th>Повинно бути
            <th>Факт
            <th>Запланована дата
            <th>Фактична дата
        </tr>
        <g:each in="${reportInstance.supReports}" var="subReportInstance">
            <tr>
                <td>
                    ${subReportInstance.merchType.name}
                </td>
                <td>
                    ${subReportInstance.supposedToBe}
                </td>
                <td>
                    ${subReportInstance.fact}
                </td>
                <td>
                    <g:formatDate format="dd.MM.yyyy" date="${subReportInstance.plannedDate}"/>
                </td>
                <td>
                    <g:formatDate format="dd.MM.yyyy" date="${subReportInstance.realDate}"/>
                </td>
            </tr>
        </g:each>
    </table>
    <br>
</div>
</body>
</html>