grails-app/domain/inventorysystem/MerchType.groovy
package inventorysystem

import inventorysystem.enums.Repeat

class MerchType {

    String name
    Repeat repeat
    Integer daysInterval
    static hasMany = [dates: Date]

    static constraints = {
        name (blank: false, unique: true)
        repeat (blank: false, enumType: 'ordinal')
        daysInterval nullable: true
        dates nullable: true
    }
}

grails-app/domain/inventorysystem/Outlet.groovy
package inventorysystem

class Outlet {

    String address
    String phoneNumber
    static hasMany = [merchTypes : MerchType]

    static constraints = {
        address (blank: false, unique: true)
        phoneNumber (nullable: true)
        merchTypes (nullable: true)
    }
}

grails-app/controllers/inventorysystem/OutletController.groovy
package inventorysystem



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class OutletController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Outlet.list(params), model: [outletInstanceCount: Outlet.count()]
    }

    def show(Outlet outletInstance) {
        respond outletInstance
    }

    def create() {
        respond new Outlet(params), model: [merchTypeList: MerchType.findAll()]
    }

    @Transactional
    def save(Outlet outletInstance) {
        params.list("merchType")?.each {outletInstance.addToMerchTypes(MerchType.get(it.toLong()))}
        if (outletInstance == null) {
            notFound()
            return
        }

        if (outletInstance.hasErrors()) {
            respond outletInstance.errors, view: 'create'
            return
        }

        outletInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'outletInstance.label', default: 'Outlet'), outletInstance.id])
                redirect outletInstance
            }
            '*' { respond outletInstance, [status: CREATED] }
        }
    }

    def edit(Outlet outletInstance) {
        respond outletInstance, model: [merchTypeList: MerchType.findAll()]
    }

    @Transactional
    def update(Outlet outletInstance) {
        outletInstance?.merchTypes?.clear()
        params.list("merchType")?.each {outletInstance.addToMerchTypes(MerchType.get(it.toLong()))}
        if (outletInstance == null) {
            notFound()
            return
        }

        if (outletInstance.hasErrors()) {
            respond outletInstance.errors, view: 'edit'
            return
        }

        outletInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Outlet.label', default: 'Outlet'), outletInstance.id])
                redirect outletInstance
            }
            '*' { respond outletInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Outlet outletInstance) {

        if (outletInstance == null) {
            notFound()
            return
        }

        outletInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Outlet.label', default: 'Outlet'), outletInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'outletInstance.label', default: 'Outlet'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/outlet/_form.gsp
<%@ page import="inventorysystem.Outlet" %>



<div class="fieldcontain ${hasErrors(bean: outletInstance, field: 'address', 'error')} required">
	<label for="address">
		<g:message code="outlet.address.label" default="Адреса" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="address" required="" value="${outletInstance?.address}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: outletInstance, field: 'phoneNumber', 'error')} ">
	<label for="phoneNumber">
		<g:message code="outlet.phoneNumber.label" default="Номер телефону" />
		
	</label>
	<g:textField name="phoneNumber" value="${outletInstance?.phoneNumber}"/>

</div>
<g:if test="${merchTypeList}">
    <div class="fieldcontain "><label style="width: 50%;">Оберіть типи товарів, що знаходяться на даній торговій точці:</label></div>
    <g:each in="${merchTypeList}" var="merchType">
        <div class="fieldcontain ">
            <label for="merchType">${merchType.name}</label>
            <g:checkBox name="merchType" value="${merchType.id}" checked="${outletInstance?.merchTypes?.contains(merchType)}"/>
        </div>
    </g:each>
</g:if>

<br>
<br>

grails-app/views/outlet/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>Створити торгову точку</title>
	</head>
	<body>
		<a href="#create-outlet" class="skip" tabindex="-1">Перейти до вмісту&hellip;</a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="btn btn-default" action="index">Список торгових точок</g:link></li>
			</ul>
		</div>
		<div id="create-outlet" class="content scaffold-create" role="main">
			<h1>Створити торгову точку</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${outletInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${outletInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:outletInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="Створити" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/outlet/edit.gsp
<%@ page import="inventorysystem.Outlet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>Редагувати торгову точку</title>
	</head>
	<body>
		<a href="#edit-outlet" class="skip" tabindex="-1">Перейти до вмісту&hellip;</a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="btn btn-default" action="index">Список торгових точок</g:link></li>
				<li><g:link class="btn btn-default" action="create">Створити торгову точку</g:link></li>
			</ul>
		</div>
		<div id="edit-outlet" class="content scaffold-edit" role="main">
			<h1>Редагувати торгову точку</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${outletInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${outletInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:outletInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${outletInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="Зберегти" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/outlet/index.gsp
<%@ page import="inventorysystem.Outlet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>Список торгових точок</title>
	</head>
	<body>
		<a href="#list-outlet" class="skip" tabindex="-1">Перейти до вмісту&hellip;</a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="btn btn-default" action="create">Створити торгову точку</g:link></li>
			</ul>
		</div>
		<div id="list-outlet" class="content scaffold-list" role="main">
			<h1>Список торгових точок</h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="address" title="${message(code: 'outlet.address.label', default: 'Адреса')}" />
					
						<g:sortableColumn property="phoneNumber" title="${message(code: 'outlet.phoneNumber.label', default: 'Номер телефону')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${outletInstanceList}" status="i" var="outletInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${outletInstance.id}">${fieldValue(bean: outletInstance, field: "address")}</g:link></td>
					
						<td>${fieldValue(bean: outletInstance, field: "phoneNumber")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${outletInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/outlet/show.gsp
<%@ page import="inventorysystem.Outlet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>Торгова точка</title>
	</head>
	<body>
		<a href="#show-outlet" class="skip" tabindex="-1">Перейти до вмісту&hellip;</a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="btn btn-default" action="index">Список торгових точок</g:link></li>
				<li><g:link class="btn btn-default" action="create">Створити торгову точку</g:link></li>
			</ul>
		</div>
		<div id="show-outlet" class="content scaffold-show" role="main">
			<h1>Торгова точка</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list outlet">
			
				<g:if test="${outletInstance?.address}">
				<li class="fieldcontain">
					<span id="address-label" class="property-label"><g:message code="outlet.address.label" default="Адреса" /></span>
					
						<span class="property-value" aria-labelledby="address-label"><g:fieldValue bean="${outletInstance}" field="address"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${outletInstance?.phoneNumber}">
				<li class="fieldcontain">
					<span id="phoneNumber-label" class="property-label"><g:message code="outlet.phoneNumber.label" default="Номер телефону" /></span>
					
						<span class="property-value" aria-labelledby="phoneNumber-label"><g:fieldValue bean="${outletInstance}" field="phoneNumber"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:outletInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${outletInstance}">Редагувати</g:link>
					<g:actionSubmit class="delete" action="delete" value="Видалити" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Ви впевнені?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>